service: movie-crawler

frameworkVersion: "2"
provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  profile: serverless
  region: ap-northeast-2

functions:
  email:
    handler: index.handler
    events:
      - http:
          path: movie-crawl
          method: GET
          cors: true
